In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from skimage.io import imread

In [6]:
data = [6, 7.5, 8, 0, 1]


In [18]:
data=[[1,2,3,4],[5,6,7,8]]

In [19]:
np.array(data).shape

(2, 4)

In [15]:
data.shape


AttributeError: 'list' object has no attribute 'shape'

In [21]:
print(np.zeros(10), '\n')
print(np.zeros((3, 6)), '\n')
print(np.eye(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)


In [23]:
arr1

array([1., 2., 3.])

In [24]:
arr2

array([1, 2, 3], dtype=int32)

In [25]:
'''
You can explicitly convert or cast an array from one dtype to another using ndarray’s
astype method:
'''
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype, '\n')

float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64 

float64


In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
help('0astype)

NameError: name 'astype' is not defined

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64
float64


In [6]:
'''
If I cast some floating-point
numbers to be of integer dtype, the decimal part will be truncated:
'''
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.astype(np.int32))

[ 3 -1 -2  0 12 10]


In [18]:
'''With higher dimensional arrays, you have many more options. In a two-dimensional
array, the elements at each index are no longer scalars but rather one-dimensional
arrays:
'''
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]])
print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0, 2]) # either way is fine

[7 8 9]
3
3


In [19]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
arr2d[:4,2:]

array([[ 3],
       [ 6],
       [ 9],
       [12]])

In [29]:
'''
For higher dimensional arrays, transpose will accept a tuple of axis numbers to per‐
mute the axes (for extra mind bending):
'''
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [39]:
arr.transpose((2, 1, 0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [40]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

'''Suppose we wanted to take a value from xarr whenever the corresponding value in
cond is True, and otherwise take the value from yarr. A list comprehension doing
this might look like:'''

'Suppose we wanted to take a value from xarr whenever the corresponding value in\ncond is True, and otherwise take the value from yarr. A list comprehension doing\nthis might look like:'

In [41]:
result=[(x if c else y) for x,y,c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [42]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [45]:
arr = np.random.randint((5, 4))
print(arr)

[1 3]


In [46]:
import random

print(random.randint(3, 9))

7


In [48]:
mat1 = np.arange(4).reshape(2,2)
mat1

array([[0, 1],
       [2, 3]])

In [49]:
mat2 = (np.arange(4)*2).reshape(2,2)
mat2

array([[0, 2],
       [4, 6]])

In [50]:
mat3 = (np.arange(4)*3).reshape(2,2)
mat3

array([[0, 3],
       [6, 9]])

In [51]:
print(np.linalg.multi_dot( [mat1, mat2, mat3] ))

[[ 36  66]
 [132 234]]


In [52]:
a = np.array([[3, 1],[1, 2]])
b = np.array([9, 8])
''' Checking if system of equation has unique solution '''
print(np.linalg.det(a)) 
# 5.0
''' Since det = 5 which is non-zero. Hence, we have unique solutions
 Finding unique solution '''
print(np.linalg.solve(a, b))
# [ 2.  3.]
''' Calculating Inverse: Since, determinant is non-zero 
 hence, matrix is invertible '''
print(np.linalg.inv(a))
# [[ 0.4 -0.2]
#  [-0.2  0.6]]
''' Calculating Rank of the matrix '''
print(np.linalg.matrix_rank(a))
# 2 

5.000000000000001
[2. 3.]
[[ 0.4 -0.2]
 [-0.2  0.6]]
2
